name: CI NPM

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract tag version
        run: |
          echo "Building on branch ${GITHUB_REF}"
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          git push --delete origin "${GITHUB_REF#refs/tags/}"
          git tag -d "${GITHUB_REF#refs/tags/}"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Run CI
        run: yarn ci

      - name: NPM Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn publish --access public --new-version ${{ env.TAG_VERSION }}
          git push origin "v${{ env.TAG_VERSION }}"
          git fetch origin master
          git checkout master
          git reset --hard "v${{ env.TAG_VERSION }}"
          git push origin master

      - name: Github Releases
        uses: softprops/action-gh-release@v1
        with:
          body: 'Release created automatically.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
